modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="opacbonusclaims"
version="1.1.0"
displayName="OPAC Bonus Claims"
authors="Mapter"
description='''
Addon for Open Parties and Claims that adds items allowing players to obtain bonus claims.
'''

[[dependencies.opacbonusclaims]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="AFTER"
side="BOTH"

[[dependencies.opacbonusclaims]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.opacbonusclaims]]
modId="openpartiesandclaims"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
